compressionLevel: mixed

enableGlobalCache: false

npmRegistryServer: "https://registry.npmjs.org"

npmRegistries:
  "//registry.npmjs.org":
    npmAuthToken: "${NPM_TOKEN}"

packageExtensions:
  docusaurus-plugin-image-zoom@1.0.1:
    peerDependencies:
      tslib: "*"

pnpEnableEsmLoader: true

supportedArchitectures:
  os:
    - current
    - linux
    - darwin
    - win32

yarnPath: .yarn/releases/yarn-4.8.1.cjs
