compressionLevel: mixed

enableGlobalCache: false

npmAuthToken: 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

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  docusaurus-plugin-image-zoom@1.0.1:
    peerDependencies:
      tslib: "*"

pnpEnableEsmLoader: true

supportedArchitectures:
  os:
    - current
    - linux
    - darwin
    - win32

yarnPath: .yarn/releases/yarn-4.8.1.cjs
