compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  docusaurus-plugin-image-zoom@1.0.1:
    peerDependencies:
      tslib: "*"

pnpEnableEsmLoader: true

supportedArchitectures:
  os:
    - current
    - linux
    - darwin
    - win32

yarnPath: .yarn/releases/yarn-4.4.0.cjs
